.github/workflows/release.yaml

* update chart relase action
* switch to helm install action

update chart relase action

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Signed-off-by: Prabhu Jayakumar <j.prabhu91@gmail.com>
Fixes #14

Configure ssl for database connection

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Hello,
I needed to add a securityContext for the unleash deployment.
By default this changes nothing but now the securityContext can be overridden if needed.
Cheers

Add possibility to configure a securityContext

---

charts/unleash/Chart.yaml
charts/unleash/values.yaml

Hi,
I would like to change to an example which works because I was struggling with implementing the custom google authentication. If we want to customize the logic of authentication, we just enable the example code.

Fix configmap example in values.yaml

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

`deployment.yaml` supports initContainers

Added support for initContainers

---

.github/ct.yaml
.github/kubeval.sh
.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/sync-readme.yaml
README.md

note: some of this is deeper than I know about. I'd love to get some
input on whether all of these changes should be the way they are.

chore: update workflows, links, code for master -> main

---

.github/workflows/ci.yaml
charts/unleash/Chart.yaml
charts/unleash/values.yaml

feat: unleash v4.12.6

---

.github/kubeval.sh
.github/workflows/ci.yaml
charts/unleash/Chart.yaml
charts/unleash/values.yaml

To better document possible values for Autoscaling, and as a response to #50 this PR adds the possible autoscaling settings to values.yaml
fixes: #50

Added autoscaling values to values.yaml

---

charts/unleash-proxy/.helmignore
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/NOTES.txt
charts/unleash-proxy/templates/_helpers.tpl
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/templates/hpa.yaml
charts/unleash-proxy/templates/ingress.yaml
charts/unleash-proxy/templates/service.yaml
charts/unleash-proxy/templates/serviceaccount.yaml
charts/unleash-proxy/templates/tests/test-connection.yaml
charts/unleash-proxy/values.yaml

Well, i didn't find any chart for unleash proxy, but i need it for my frontend, so I did it 
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml

add unleash-proxy helm chart

---

charts/unleash-proxy/Chart.yaml

Uprade unleash proxy appVersion to `v0.11.7` [release](https://github.com/Unleash/unleash-proxy/releases/tag/v0.11.7)

feat(unleash-proxy) upgrade proxy to v0.11.7

---

charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml
charts/unleash/values.yaml

Can be useful to fix Load Balancer IP in helm release in order to avoid IP changing during the reinstall of helm release or something else.
* charts/unleash/Chart.yaml
* charts/unleash/templates/service.yaml
* charts/unleash/values.yaml

Added the abbility to fix LB's ip.

---

charts/unleash/Chart.yaml

ci(helm-version): bump 2.7.4

---

.github/workflows/ci.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml
charts/unleash/values.yaml

This PR introduce some env var available in [unleash proxy configuration](https://docs.getunleash.io/sdks/unleash-proxy#configuration)
- `charts/unleash-proxy/templates/deployment.yaml`
- `charts/unleash-proxy/values.yaml`

feat(unleash-proxy): add more var env entries

---

charts/unleash-proxy/Chart.yaml

Fixes a chart linting issue (new line at end of file)

fix: Make sure chart schema validates for unleash-proxy

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

The default version of unleash being used in the chart is quite old. 4.19.4 is the latest stable with lots of bug fixes. We just upgraded our production unleash from 4.15 to 4.19.4 and all appears to be working well. Its probably time to bump the default version too.

Bump appVersion and chart version

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

Fix PostgreSQL secret name

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Bitnami PostgreSQL helm charts does not have `postgresqlDatabase`, `postgresqlUsername` and `postgresqlPassword` so the keys were changed.

Change default values for Bitnami Postgres helm chart 

---

charts/unleash-proxy/README.md

Since we were missing a README altogether for this chart, I've taken inspiration from our unleash chart, and written a README for the unleash-proxy chart.

task: add README for unleash-proxy chart

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml

missing `"` was causing 403 errors to unleash host making proxy unusable

fix: not working serverHost

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

feat: Added dbConfig.schema as a configurable property

---

charts/unleash-edge/Chart.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash/Chart.yaml

unleash: 5.4.4
unleash-edge: 11.0.2
unleash-proxy: 0.17.0

feat: bump unleash, unleash-proxy and unleash-edge versions

---

.github/ct.yaml
.github/workflows/ci.yaml
charts/unleash-edge/Chart.yaml

Don't know what happened here, but app version was not updated. Trying again.

feat: release 2.1.0 of Edge chart

---

charts/unleash-edge/Chart.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash/Chart.yaml

Updates unleash and edge. Proxy skipped for now as it fails.

chore: update versions

---

.github/workflows/release.yaml
README.md

Adds documentation about how to release the helm charts

docs: document release process

---

charts/unleash/Chart.yaml

This bumps Unleash to its latest version

chore: upgrade unleash version

---

charts/unleash-edge/Chart.yaml

chore: bump edge to 19.0.0

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/pdb.yaml
charts/unleash-edge/values.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/pdb.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/pdb.yaml
charts/unleash/values.yaml

Add support for PodDisruptionBudget

feat: add pod-disruption-budget support

---

charts/unleash/Chart.yaml
charts/unleash/values.yaml

As we plan to remove our passport dependencies https://github.com/Unleash/unleash/pull/7159 starting from 6.0.0, the current comments in values.yaml no longer holds. Unleash will no longer include passport libraries and as such, the suggested index.js configmap will not work at all.

docs: Update values.yaml comments to point to community images

---

charts/unleash/values.yaml

Unleash should work well if example resources are being used, so lets bump them so they can handle some data and traffic.

chore(examples): more beefy examples

---

charts/unleash/Chart.yaml

chore: bump chart version

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/examples/hostaliases.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

Adds hostAliases as a possible value.
Fixes #156

fix: add hostaliases

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml

https://github.com/Unleash/helm-charts/pull/152 introduced a bug which this subsequent PR addresses. Unfortunately `helm lint` does not catch some errors like this, but running `helm template...` does
Closes #

Fix deployment pod labels

---

charts/unleash-edge/Chart.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/examples/environmentVariables.yaml

What the title says. This bumps to most recent version released at this time

chore: bump all charts to most recent versions of image

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Allow to add extra sidecar containers to unleash deployment.

feat: Add extraContainers to unleash

---

charts/unleash/Chart.yaml

Updates to allow usage of unleash 6.6.0

Unleash 6.6.0

---

charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml

use nindent for indenting service annotations

---

charts/unleash-edge/Chart.yaml

To simplify using a newer version of Edge.

task: bump Edge version to 19.10.1

---

charts/unleash/Chart.yaml

chore(version): Updated Unleash to 7.2.2
