README.md
charts/unleash/Chart.yaml
charts/unleash/README.md

Signed-off-by: André Bauer <monotek23@gmail.com>
fix the link to the helm repo in the readme.
needs to be merged after: https://github.com/Unleash/helm-charts/pull/7

fix repo links in readme

---

charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml
charts/unleash/values.yaml

- It is not possible to create the service type "LoadBalancer" with annotations and loadBalancerSourceRanges
- Add in template options to create service with annotations and loadBalancerSourceRanges
- Add options in service template
- Add new options in valeus

[Unleash] Add annotations and loadBalancerSourceRanges in service template

---

charts/unleash/templates/ingress.yaml
charts/unleash/values.yaml

`apiVersion: networking.k8s.io/v1beta1` is deprecated for a long time and removed in Kubernetes 1.22.
Refresh ingress template using current default template from `helm create`.

Support up-to-date apiVersion in ingress template

---

charts/unleash/templates/deployment.yaml

This PR is to update the template of the `deployment` resource kind. We shouldn't set the `replicas` attribute if the HPA is enabled. This is needed when we manage the deployment of Unleash helm chart via a declarative GitOps tool like ArgoCD. The changes help to avoid the conflicts between resources (HPA & deployment's replicas). Otherwise, they will fight over the correct value.
None
None

chore: don't set the replicas if HPA is enabled

---

charts/unleash/Chart.yaml

This bumps the chart version, so we get a new version released that includes the fix for not using replicas in deployment descriptor if an HPA is set up

Update chart to 2.6.1 including fix for replicas/hpa

---

.github/workflows/ci.yaml

This PR updates our testing strategy to test k8s 1.19-1.24 instead of the current 1.16-1.20 versions.
kubernetes 1.21 is reading End of Life June 28 2022 (See https://kubernetes.io/releases/), so this PR is less aggressive than it could (should?) be, but at least drops 1.16-1.18.

task: Updates which k8s versions we test against

---

.github/kubeval.sh
.github/workflows/ci.yaml
README.md

So, we've decided to support the versions that are currently in active support mode according to https://kubernetes.io/releases and https://kubernetes.io/releases/patch-releases/#support-period so this PR promotes our test clusters to 1.22, 1.23 and 1.24 (1.21 reached EoL today)

task: updated to reflect decision regarding support strategy

---

CONTRIBUTING.md

Adds a file describing the rough steps around contributing.
As was mentioned in #50, the readme link to contribution guidelines is broken: the file it points to doesn't exist. I tried looking for it in the git history, but couldn't find it.
Copies most of the content from the unleash/unleash contribution guide, but makes a few adjustments to make it more appropriate to this repo.

meta: add contributing.md

---

charts/unleash/Chart.yaml

This change removes the `unleash-docker` repo from the list of sources
in the `unleash/Chart.yaml` file.
The `unleash-docker` repo was archived just a few days ago because the
main `unleash` repo now contains a docker file.

chore: Remove unleash-docker repo as a source

---

.github/workflows/ci.yaml

* Fix CI `super-linter` 4.10.x as [described in super-linter issue](https://github.com/github/super-linter/issues/1397) and [from super-linter examples](https://github.com/github/super-linter/blob/main/README.md?plain=1#L169):
> Full git history is needed to get a proper list of changed files within `super-linter`
* Fix [github action deprecation](https://github.com/Unleash/helm-charts/actions/runs/4017009121/jobs/6900794768#step:4:74)
```
2023-01-26 16:17:32 [ERROR]   Found errors in [actionlint] linter!
2023-01-26 16:17:32 [ERROR]   Error code: 1. Command output:
------
.github/workflows/ci.yaml:112:14: workflow command "set-output" was deprecated. use `echo "{name}={value}" >> $GITHUB_OUTPUT` instead: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-action …
```

fix: super-linter fails in 4.10.x

---

charts/unleash/Chart.yaml

Updates the postgresql dependency to most recent version.
10.16.2 was no longer resolveable from charts.bitnami.com, so this bumps us to 12.1.6 which is still resolveable

fix: Updated postgresql dependency for unleash

---

charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml

I added the possibility to configure the liveness and the readiness probes for the Unleash Proxy.
This is important because if one hosts the proxy in a subpath, e.g. `https://mycompany.com/app/unleash-proxy`,
then the variable `PROXY_BASE_PATH` needs to be configured in the `env:` block of the `values.yaml` AND the path for the liveness and readiness probes needs to be updated too.
Before this pull request the liveness and readiness path is hardcoded to `/proxy/health`.
Now it is possible to configure it.
I simply copied the corresponding block from the `deployment.yaml` file for the Helm chart for the Unleash backend.
I also copied the default values to the `values.yaml`.
This PR does not close any issues.
Both files `deployment.yaml` and `values.yaml` are equally important. This is a …

Add possibility to configure liveness and readiness probes for Unleash Proxy

---

charts/unleash-proxy/Chart.yaml

Updates default appVersion to most recently released unleash-proxy, as well as bump the minor for the Chart, to have a release including changes for configuring health and readiness checks.

fix: bumped unleash-proxy chart version

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml

This makes it possible to mount secrets in /mnt/secrets. This is required in order to supply custom ca certificates

feat: proxy support mounting secrets

---

charts/unleash-edge/Chart.yaml

Upgrading the Edge chart to v7.0.0, which includes all the latest yggdrasil fixes, as well as the code needed for allowing Edge to create client tokens for frontend tokens to stop 511's appearing.

feat: Bump Edge to v7.0.0

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/service.yaml
charts/unleash-edge/values.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/service.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml
charts/unleash/values.yaml

Add optional 'service.nodePort' values to allow binding NodePort services for all charts via a static NodePort, as per https://kubernetes.io/docs/concepts/services-networking/service/#nodeport-custom-port
Closes #87 
`charts/*/templates/service.yaml`

feat: Add support for static NodePort services

---

charts/unleash/README.md

This change adds a note to the Unleash readme that we recommend you
use a separate postgres instance instead of the one bundled with the chart.

docs: recommend using a separate postgres instance

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-edge/values.yaml

This allows BASE_PATH enviornment variable changes to be reflected in the values.yaml file. Without this, k8s will attempt to hit /internal-backstage/health, while the helm-edge application is reporting health values at /BASE_PATH/internal-backstage/health.
Closes #96
This change is small, important files are deployment.yaml and values.yaml
It could be worth discussing creating a true value for BASE_PATH in the values.yaml file instead of having to duplicate the basepath value in the helm values chart.

feat: Add support for modifying edge probe values

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/service.yaml
charts/unleash-edge/values.yaml

As reported in #106 our Edge service always used the same targetPort as the port in the container, this PR makes it configurable while defaulting to the same as it used to.
@yuvals41 - Will this solve your issue?
fixes: #106

fix(unleash-edge): Make target port configurable

---

.github/workflows/ci.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Copied from https://github.com/Unleash/helm-charts/pull/95 to lint it
SSL configuration is not able to be passed via environment variable in the helm chart. Any attempt to pass stringified JSON ([docs](https://docs.getunleash.io/reference/deploy/configuring-unleash#dbssl-vs-database_ssl-options)) results in a Helm parsing error.
Semi related to #94
Fixes #102

chore: allow ssl configuration

---

charts/unleash-edge/Chart.yaml

A few weeks ago, unleash-edge#341 was fixed and Unleash Edge 16.0.4 was released. However, the Helm chart still uses Edge 16.0.3.

chore: update Edge version

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/tests/test-connection.yaml

Update `test-connection.yaml` in the Unleash proxy Helm chart to use an authenticated route.
The currently used route `/proxy/health` does not require authentication. The Authentication header is ignored for this route. Even if there's an issue with the way client shared secrets are configured, the `test-connection.yaml` test will succeed.
Using the `/proxy` route (which does require authentication) allows testing a shared secret.
This change implements the recommended method to test the proxy deployment from
https://docs.getunleash.io/how-to/how-to-run-the-unleash-proxy#verify-that-the-proxy-is-working
Also update the way `wget` is called (the Authentication header was not correctly set, but as it was ignored this mistake was not visible).
Note: The same Helm value is used to configure …

feat(proxy): test proxy connection with an authenticated route

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/values.yaml

Setting up default "requests" makes it impossible to omit certain portions of "requests" in local `values.yaml` file, e.g. not setting `resources.limits.cpu` is impossible. For more information see #121 
Comment taken from Unleash template to be consistent:
https://github.com/Unleash/helm-charts/blob/4cd3a4a2afec1a3048ccbafc2a7c869c64393ed4/charts/unleash/values.yaml#L193-L198
Closes #121

bug: don't set default "requests" in Unleash Edge chart values.yaml

---

.github/workflows/ci.yaml

This was added recently to get tap results printed to stdout, but we already add the tap results to the summary of the workflow, so that this breaking should cause the build to break seems wrong to me.
This PR removes the stdout printing of tap, but keeps the add test-summary action so we still get tap results attached to the workflow run.

fix: Don't fail builds just because we can't print a tap file

---

charts/unleash/Chart.yaml
charts/unleash/templates/_helpers.tpl
charts/unleash/templates/deployment.yaml
charts/unleash/templates/service.yaml
charts/unleash/templates/serviceAccount.yaml
charts/unleash/values.yaml

feat: Support optional cloudsql-proxy sidecar

---

README.md
charts/unleash/Chart.yaml
charts/unleash/ci/unleash-values.yaml
charts/unleash/templates/deployment.yaml

In this PR: https://github.com/Unleash/helm-charts/pull/125, a bug was introduced related to injecting secret into pods if passed from the values file. This PR fixes the regression and adds test for secret injection.

fix: Regression with secrets fullname

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-edge/values.yaml

This PR adds a mechanism for users to define a startup probe where failure to hot load edge containers with flags blocks startup.
If we like this approach, we copy the simplification to other charts.

feat: Add optional startup probe and simplify liveness and readiness probes

---

charts/unleash-edge/Chart.yaml

Bumps Unleash Edge version to the latest `v17.1.0`.

chore: bump edge version to v17.1.0

---

charts/unleash/Chart.yaml
charts/unleash/examples/existingSecrets.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Our previous implementation for existingSecrets expected a string from our values file that had to be escaped using the `|`  to mark a block style with newlines preserved.
This PR changes to expect a list of secret key references, and then extracts the values from the secret reference. See the example file.

fix: make existing secrets an array of secret refs

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

- Unleash looks for DATABASE_NAME, it does not look for DATABASE, so this has actually not been working earlier
fixes: #136

fix: set DATABASE_NAME instead of DATABASE.

---

charts/unleash/Chart.yaml
charts/unleash/examples/sslConfigFile.yaml
charts/unleash/examples/sslFiles.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Related to Unleash#6718 - This allows Helm users to configure the new environment variables.
It will not work on current 5.11.3, will have to wait for 5.12.0 before it becomes relevant.

feat: added configurable DATABASE_SSL_* possibilities

---

charts/unleash/Chart.yaml
charts/unleash/templates/service.yaml
charts/unleash/values.yaml

This allows you to make the target port customisable for the unleash service.
There is no open issue for it.. but it is the same as this change that was done for the unleash-edge helm chart - https://github.com/Unleash/helm-charts/issues/106

make target port customisable for unleash helm chart

---

charts/unleash/Chart.yaml
charts/unleash/examples/debugLogging.yaml
charts/unleash/templates/deployment.yaml

As the title says, our included postgres chart does not configure SSL connections, so DATABASE_SSL needs to be set to false when starting with included chart. If you've made the effort to configure ssl, you can still override DATABASE_SSL with dbConfig.ssl even with postgres enabled.

fix: ssl needs to be disabled when postgres enabled

---

charts/unleash-edge/Chart.yaml

Include latest bugfix in our helm-chart

chore: Bump default edge version to latest bugfix

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.github/workflows/sync-readme.yaml

Since 1.26 reached eol in February 2024, this PR includes it, but we'll need to do another shift this fall, to include 1.30, and exclude 1.26

chore: bumped to supported k8s versions

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

This allows you to use nameOverride if you don't want to use the Chart.name as your container name.
fixes: #153

fix: Include name helper for container name in all three charts

---

.github/workflows/ci.yaml
charts/unleash-edge/Chart.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

As it says on the tin. Makes Edge 19.2.0 and Unleash 6.0.6 the new defaults for the charts

task: updates versions of edge and unleash

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Adds support for topologySpreadConstraints to the unleash chart. This was copied [from the unleash-edge helm chart
](https://github.com/search?q=repo%3AUnleash%2Fhelm-charts+topologySpreadConstraints+path%3A%2F%5Echarts%5C%2Funleash-edge%5C%2F%2F&type=code)

Allow topologySpreadConstraints for unleash

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

This is related to the bug described in #144. When using an external postgres without SSL the Unleash Pods throw the following error:
```
Error: The server does not support SSL connections                                                                                                                                                             
at Socket.<anonymous> (/unleash/node_modules/pg/lib/connection.js:77:37)                                                                                                                                   
at Object.onceWrapper (node:events:634:26)                                                                                                                                                                 
at Socket.emit (node:events:519:28) …
```

fix(unleash): set DATABASE_SSL to false as default

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml

Continues work from https://github.com/Unleash/helm-charts/pull/158 to add labelSelector and matchLabelKeys to topologySpreadConstraints. The labelSelector is used to track the pods that are used for the topologySpreadConstraints calculation. matchLabelKeys is used to only use the pods in the current version of the deployments replicaset.
More details about matchLabelKeys can be found here:
- https://kubernetes.io/blog/2023/04/17/fine-grained-pod-topology-spread-features-beta/#kep-3243-respect-pod-topology-spread-after-rolling-upgrades
- https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

Add labelSelector and matchLabelKeys to topologySpreadConstraints

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml

There are DNS issues in Alpine, which affects Unleash Proxy deployments on some Kubernetes clusters. Possible workaround is adding `dnsConfig` to Pod spec:
```yaml
dnsConfig:
options:
- name: ndots
value: "1"
```
This PR allows configuring `dnsConfig` in Unleash Proxy chart to address that.

Allow dnsConfig for unleash proxy

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-edge/values.yaml
charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

For each chart, this adds a new value called `deploymentAnnotations`. This allows users to set annotations on the Deployment object similarly to how `podAnnotations` sets them on the Pods.
I would like to use this to set an annotation that allows [Reloader](https://github.com/stakater/Reloader) to refresh my instance of Unleash Proxy if and when the secret containing the client key gets changed. I added it to each chart for consistency.
No open issue
I followed the implementation of `podAnnotations` here so that the 'with' keyword would only add the annotations block when `deploymentAnnotations` is not blank. 
Also bumped each Chart version number. Let me know if this is not desired.

add deploymentAnnotations to each chart

---

charts/unleash-proxy/Chart.yaml
charts/unleash-proxy/examples/addingExistingSecrets.yaml
charts/unleash-proxy/templates/deployment.yaml
charts/unleash-proxy/values.yaml
charts/unleash/Chart.yaml
charts/unleash/examples/existingSecrets.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

feat: added volume and volume mounts

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Adds Pod Security Context variable to Unleash helm chart
Thank you!

feat: add podSecurityContext to unleash chart

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/ci/unleash-edge-values.yaml
charts/unleash-edge/templates/deployment.yaml
charts/unleash-edge/values.yaml

This PR fixes the implementation of `existingSecrets` in the unleash-edge Helm chart which currently causes Kubernetes validation errors when deploying with secret configurations. The issue is documented in [unleash#9111](https://github.com/Unleash/unleash/issues/9111).
1. Modified deploment.yaml default to use envFrom to load secrets
```yaml
{{- if Values.existingSecrets }}
envFrom:
- secretRef:
name: {{ .Values.existingSecrets }}
{{- end }}
```
2. Updated the deployment template to use `envFrom` instead of trying to merge secrets into `env` section, which prevents validation errors with environment variables.
- Deployed chart with empty secrets configuration (works)
- Deployed chart with secrets configured:
```yaml
existingSecrets: custom-user-secret  # references existing secret
```
- …

Potential fix for issue https://github.com/Unleash/unleash/issues/9111

---

charts/unleash/Chart.yaml
charts/unleash/templates/deployment.yaml
charts/unleash/values.yaml

Add a databaseSecrets value to populate the DATABASE_ host, port, username and password vars from secret file.
Closes #183

Add a databaseSecrets value to populate the DATABASE variables

---

charts/unleash/Chart.yaml

Ref #191 
Though we do allow you to override the image tag in your values file. This now defaults to Unleash 6.10.0

task: bump Unleash version to 6.10.0

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/values.yaml

Since we migrated to chef build, the docker image now puts the binary in /app/unleash-edge instead of /unleash-edge. This updates the health check to use the correct path. 
fixes #194

fix: docker image has moved binary, update checks

---

charts/unleash-edge/Chart.yaml

As the comment says. We just released v19.11.1 to fix a bug with failure to initialize TLS for redis connections. So this PR bumps Edge to that version.

task: update chart with newest edge version

---

charts/unleash-edge/Chart.yaml
charts/unleash-edge/examples/extraLabelsForServiceMonitor.yaml
charts/unleash-edge/templates/serviceMonitor.yaml
charts/unleash-edge/values.yaml
charts/unleash/Chart.yaml
charts/unleash/templates/serviceMonitor.yaml
charts/unleash/values.yaml

As requested in #196 . This PR adds support for ServiceMonitors for Unleash and Unleash-Edge charts.
Disabled by default, but enabled by setting serviceMonitor.enabled=true.
Should fix #196

feat: added serviceMonitor support for unleash and unleash-edge charts
